### ISSUE TITLE
make the script more verbose

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/action-publish#2]
currently the output of this action is pretty silent. here is example of a run:
```
Run threefoldtech/action-publish@v1-release
  with:
    root: /tmp/archive
    token: ***
    name: zos-.tar.gz
  env:
    GOROOT: /opt/hostedtoolcache/go/1.13.1/x64
tar -czf /tmp/13a992324b85c0a3589984ee29ac410a. -C /tmp/archive .
```
There is not much usefull information. Would be cool that the script print at least the url of the created flist.
